DROP TABLE IF EXISTS PERSONNE;
CREATE TABLE PERSONNE(ID INT PRIMARY KEY, NAME VARCHAR(255), AGE INT);
INSERT INTO PERSONNE VALUES(1, 'JEAN', 45);
INSERT INTO PERSONNE VALUES(2, 'MICHEL', 25);
INSERT INTO PERSONNE VALUES(3, 'GOKU', 32);